apiVersion: v2
appVersion: 1.16.0
description: A Helm chart for Kubernetes to deploy Laravel applications
name: laravel
type: application
version: 2.6.0
dependencies:
  - name: postgresql
    condition: postgresql.enabled
    repository: https://charts.bitnami.com/bitnami
    version: ^15.5.18
  - name: mysql
    condition: mysql.enabled
    repository: https://charts.bitnami.com/bitnami
    version: ^11.1.17
  - name: redis
    condition: redis.enabled
    repository: https://charts.bitnami.com/bitnami
    version: ^19.6.2
