{{- if .Values.cronjobs.enabled -}}
{{- $root := . -}}
{{- range .Values.cronjobs.schedulers }}
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ regexReplaceAll "_" .name "-" }}-cronjob
  labels:
    {{- include "laravel.labels" $root | nindent 4 }}
spec:
  schedule: "{{ .schedule | default $root.Values.cronjobs.schedule }}"
  concurrencyPolicy: "{{ .concurrencyPolicy | default $root.Values.cronjobs.concurrencyPolicy }}"
  startingDeadlineSeconds: {{ .startingDeadlineSeconds | default $root.Values.cronjobs.startingDeadlineSeconds }}
  successfulJobsHistoryLimit: {{ .successfulJobsHistoryLimit | default $root.Values.cronjobs.successfulJobsHistoryLimit }}
  jobTemplate:
    spec:
      backoffLimit: 2
      template:
        metadata:
          labels:
            {{- include "laravel.labels" $root | nindent 12 }}
        spec:
          {{- with $root.Values.imagePullSecrets }}
          imagePullSecrets:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          serviceAccountName: {{ include "laravel.serviceAccountName" $root }}
          securityContext:
            {{- toYaml $root.Values.podSecurityContext | nindent 12 }}
          containers:
          - name: {{ regexReplaceAll "_" .name "-" }}-cronjob
            securityContext:
              {{- toYaml $root.Values.securityContext | nindent 14 }}
            env:
              {{- toYaml $root.Values.extraEnvVars | nindent 14 }}
            image: "{{ $root.Values.image.repository }}:{{ $root.Values.image.tag }}"
            imagePullPolicy: {{ $root.Values.image.pullPolicy }}
            {{- if $root.Values.volumeMounts }}
            volumeMounts:
              {{- toYaml $root.Values.volumeMounts | nindent 14 }}
            {{- end }}
            {{- if .resources }}
            resources: {{- toYaml .resources | nindent 14 }}
            {{- else if and .resourcesPreset (ne .resourcesPreset "none") }}
            resources: {{- include "common.resources.preset" (dict "type" .resourcesPreset) | nindent 14 }}
            {{- else if $root.Values.cronjobs.resources }}
            resources: {{- toYaml $root.Values.cronjobs.resources | nindent 14 }}
            {{- else if and $root.Values.cronjobs.resourcesPreset (ne $root.Values.cronjobs.resourcesPreset "none") }}
            resources: {{- include "common.resources.preset" (dict "type" $root.Values.cronjobs.resourcesPreset) | nindent 14 }}
            {{- end }}
            command:
              - sh
              - -c
              - {{ .cmd }}
          {{- if $root.Values.volumes }}
          volumes:
            {{- toYaml $root.Values.volumes | nindent 12 }}
          {{- end }}
          nodeSelector:
            {{- toYaml $root.Values.nodeSelector | nindent 12 }}
          restartPolicy: "{{ .restartPolicy | default $root.Values.cronjobs.restartPolicy }}"
{{- end }}
{{- end }}
