apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "laravel.fullname" . }}
  labels:
    {{- include "laravel.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "laravel.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "laravel.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "laravel.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
      {{- if .Values.logger.enabled }}
      - name: logger
        securityContext:
          {{- toYaml .Values.securityContext | nindent 10 }}
        image: "fluent/fluent-bit:latest"
        {{- if .Values.logger.resources }}
        resources: {{- toYaml .Values.logger.resources | nindent 10 }}
        {{- else if and .Values.logger.resourcesPreset (ne .Values.logger.resourcesPreset "none") }}
        resources: {{- include "common.resources.preset" (dict "type" .Values.logger.resourcesPreset) | nindent 10 }}
        {{- end }}
        volumeMounts:
        - name: logs
          mountPath: "/logs"
        - name: fluent-bit-conf
          mountPath: "/fluent-bit/etc/fluent-bit.conf"
          subPath: "fluent-bit.conf"
        - name: fluent-bit-conf
          mountPath: "/fluent-bit/etc/parsers.conf"
          subPath: "parsers.conf"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
      {{- end }}
      - name: {{ .Chart.Name }}
        securityContext:
          {{- toYaml .Values.securityContext | nindent 10 }}
        env:
          {{- toYaml .Values.extraEnvVars | nindent 10 }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
          - name: http
            containerPort: 80
            protocol: TCP
        {{- if .Values.livenessProbe.enabled }}
        livenessProbe:
          httpGet:
            path: {{ .Values.livenessProbe.path }}
            port: {{ .Values.livenessProbe.port }}
          failureThreshold: 5
          initialDelaySeconds: 5
          periodSeconds: 20
          timeoutSeconds: 10
        {{- end }}
        {{- if .Values.readinessProbe.enabled }}
        readinessProbe:
          httpGet:
            path: {{ .Values.readinessProbe.path }}
            port: {{ .Values.readinessProbe.port }}
          initialDelaySeconds: 5
          periodSeconds: 20
          timeoutSeconds: 10
        {{- end }}
        {{- if .Values.volumeMounts }}
        volumeMounts:
          {{- toYaml .Values.volumeMounts | nindent 10 }}
        {{- end }}
        {{- if .Values.resources }}
        resources: {{- toYaml .Values.resources | nindent 10 }}
        {{- else if and .Values.resourcesPreset (ne .Values.resourcesPreset "none") }}
        resources: {{- include "common.resources.preset" (dict "type" .Values.resourcesPreset) | nindent 10 }}
        {{- end }}
      {{- if or .Values.volumes .Values.logger.enabled }}
      volumes:
        {{- if .Values.volumes }}
        {{- toYaml .Values.volumes | nindent 8 }}
        {{- end }}
        {{- if .Values.logger.enabled }}
        - name: fluent-bit-conf
          configMap:
             name: {{ include "laravel.fullname" . }}-fluentbit-configs
             items:
               - key: fluent-bit.conf
                 path: fluent-bit.conf
               - key: parsers.conf
                 path: parsers.conf
        {{- end }}
      {{- end }}
      nodeSelector:
        {{- toYaml .Values.nodeSelector | nindent 8 }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
