{{- if .Values.workers.enabled -}}
{{- $root := . -}}
{{- range .Values.workers.items }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ regexReplaceAll "_" .name "-" }}-worker
  labels:
    {{- $workerName := .name }}
    {{- include "laravel.workerLabels" (dict "Values" $root.Values "Chart" $root.Chart "Release" $root.Release "workerName" $workerName) | nindent 4 }}
spec:
  replicas: {{ .replicaCount | default 1 }}
  selector:
    matchLabels:
      {{- include "laravel.workerSelectorLabels" (dict "Values" $root.Values "Chart" $root.Chart "Release" $root.Release "workerName" $workerName) | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "laravel.workerSelectorLabels" (dict "Values" $root.Values "Chart" $root.Chart "Release" $root.Release "workerName" $workerName) | nindent 8 }}
    spec:
      {{- with $root.Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "laravel.serviceAccountName" $root }}
      securityContext:
        {{- toYaml $root.Values.podSecurityContext | nindent 8 }}
      containers:
      - name: {{ regexReplaceAll "_" .name "-" }}-worker
        securityContext:
          {{- toYaml $root.Values.securityContext | nindent 10 }}
        env:
          {{- toYaml $root.Values.extraEnvVars | nindent 10 }}
        image: "{{ $root.Values.image.repository }}:{{ $root.Values.image.tag }}"
        imagePullPolicy: IfNotPresent
        {{- if $root.Values.volumeMounts }}
        volumeMounts:
          {{- toYaml $root.Values.volumeMounts | nindent 10 }}
        {{- end }}
        {{- if .resources }}
        resources: {{- toYaml .resources | nindent 10 }}
        {{- else if and .resourcesPreset (ne .resourcesPreset "none") }}
        resources: {{- include "common.resources.preset" (dict "type" .resourcesPreset) | nindent 10 }}
        {{- else if $root.Values.workers.resources }}
        resources: {{- toYaml $root.Values.workers.resources | nindent 10 }}
        {{- else if and $root.Values.workers.resourcesPreset (ne $root.Values.workers.resourcesPreset "none") }}
        resources: {{- include "common.resources.preset" (dict "type" $root.Values.workers.resourcesPreset) | nindent 10 }}
        {{- end }}
        command:
          - sh
          - -c
          - {{ .cmd }}
      {{- if $root.Values.volumes }}
      volumes:
        {{- toYaml $root.Values.volumes | nindent 8 }}
      {{- end }}
      nodeSelector:
        {{- toYaml (.nodeSelector | default $root.Values.workers.nodeSelector | default $root.Values.nodeSelector) | nindent 8 }}
{{- end }}
{{- end }}
