{{- if .Values.mariadb.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ default "mariadb" .Values.mariadb.nameOverride }}-credentials
  labels:
    {{- include "laravel.labels" . | nindent 4 }}
type: Opaque
data:
  mariadb-root-password: {{ "secret" | b64enc | quote }}
  mariadb-password: {{ "secret" | b64enc | quote }}
{{- end -}}
